# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres-dev:
    image: postgres
    restart: always
    volumes:
      - postgres:/media/apps4/postgres/db:rw
    ports:
      - 6432:5432
    environment:
      POSTGRES_PASSWORD: devuser321
      POSTGRES_USER: devuser
      POSTGRES_DB: transcribeapp_db
      PGDATA: /media/apps4/postgres/db

volumes:
  postgres:
